services:
  vna:
    build:
      context: .
      dockerfile: Dockerfile
    image: heimdex/vna-dev:latest
    container_name: vna-dev
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - TZ=${TZ:-Asia/Seoul}
    working_dir: /app
    volumes:
      - ./app:/app/app:rw
      - ./data:/data:rw
    # Expose a port in case you add a web API later (FastAPI, etc.)
    # ports:
    #   - "8000:8000"
    stdin_open: true
    tty: true
    command: ["uv", "run", "--active", "python", "app/cli.py", "--check"]
    healthcheck:
      test: ["CMD-SHELL", "ffmpeg -version >/dev/null 2>&1 && ffprobe -version >/dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
