services:
  vna:
    build:
      context: .
      dockerfile: Dockerfile
    image: heimdex/vna-dev:latest
    container_name: vna-dev
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - TZ=${TZ:-Asia/Seoul}
    working_dir: /app
    volumes:
      - ./app:/app/app:rw
      - ./data:/data:rw
      - ./tests:/app/tests:rw
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: ["uv", "run", "--active", "fastapi", "run", "app/main.py", "--app", "app", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/health >/dev/null || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s
