services:
  postgres:
    image: postgres:15-alpine
    container_name: vna-postgres
    environment:
      POSTGRES_DB: heimdex
      POSTGRES_USER: heimdex
      POSTGRES_PASSWORD: heimdex
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: vna-redis
    ports:
      - "6379:6379"

  vna:
    build:
      context: .
      dockerfile: Dockerfile
    image: heimdex/vna-dev:latest
    container_name: vna-dev
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - TZ=${TZ:-Asia/Seoul}
      - HEIMDEX_DATABASE_URL=${HEIMDEX_DATABASE_URL:-postgresql+asyncpg://heimdex:heimdex@postgres:5432/heimdex}
      - HEIMDEX_REDIS_URL=${HEIMDEX_REDIS_URL:-redis://redis:6379/0}
      - HEIMDEX_STORAGE_BACKEND=${HEIMDEX_STORAGE_BACKEND:-local}
    working_dir: /app
    volumes:
      - ./app:/app/app:rw
      - ./data:/data:rw
      - ./tests:/app/tests:rw
      - ./derived:/app/derived:rw
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - postgres
      - redis
    command: ["uv", "run", "--active", "fastapi", "run", "app/main.py", "--app", "app", "--host", "0.0.0.0", "--port", "8000"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/v1/health >/dev/null || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:
